name: Deploy
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build step
        env:
          SERVER_URL: ${{ secrets.SERVER_URL }}
          BASE_API_URL: ${{ secrets.BASE_API_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
        run: "deno task build"

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "podcastap"
          entrypoint: "main.ts"
          root: "src"
          env: GITHUB_BRANCH=${{ steps.extract_branch.outputs.branch }}
